version: '3.6'
services:
  haur:
    container_name: haur
    restart: always
    image: ${IMAGE}
    networks:
      - dc-net
    environment:
#      DB_NAME: haur

      #CONFIG SERVER
      CONFIG_SERVER_URL: http://config_server
      SERVICE_NAME: haur
      NAMESPACE: prod
      M_TOKEN: ${M_TOKEN}
      #END CONFIG SERVER

#    ports:
#      - 82:81
networks:
  dc-net:
    external: true