// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"database/sql"
	"dc_haur/src/internal/domain"
	"dc_haur/src/internal/repo"
	"dc_haur/src/internal/service"
	"dc_haur/src/tghttp"
)

// Injectors from di.go:

func InitServices(db *sql.DB) *service.Services {
	repositories := repo.NewRepositories(db)
	botAPI := tghttp.CreateTgBot()
	botInteractor := domain.NewBotInteractor(botAPI)
	services := service.NewServices(repositories, botInteractor)
	return services
}
