name: Deploy
on:
  push:
    branches: [ "stage" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout env
      with:
        repository: Logotipiwe/dc_vars
        token: ${{secrets.PAT}}
    - name: Load env
      uses: duskmoon314/action-load-env@v1.1.0

    - name: Checkout project
      uses: actions/checkout@v3
      with:
        repository: Logotipiwe/dc_haur
        token: ${{secrets.PAT}}

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ env.DOCKER_USER }}
        password: ${{ env.DOCKER_PAT }}
    - name: Build
      id: build_push
      run: |
        ls
        export IMAGE=${{ env.DOCKER_USER }}/haur_stage:$(date +%s)
        docker build . -t ${IMAGE}
        docker push ${IMAGE}
        echo "IMAGE=${IMAGE}" >> "$GITHUB_ENV"
    - name: Upload
      uses: garygrossgarten/github-action-scp@release
      with:
        local: ./deploy
        concurrency: 20
        remote: /kuber/haur_stage
        host: ${{ env.DC_HOST }}
        username: ${{ env.SSH_USER }}
        password: ${{ env.SSH_PASSWORD }}
    - name: Deploy
      id: deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ env.DC_HOST }}
        username: ${{ env.SSH_USER }}
        password: ${{ env.SSH_PASSWORD }}
        port: 22
        script: |
          export IMAGE=${{ env.IMAGE }}
          export M_TOKEN=${{ env.M_TOKEN }}
          
          docker-compose -f /kuber/haur_stage/haur.stage.yml down --remove-orphans
          docker-compose -f /kuber/haur_stage/haur.stage.yml up -d